import java.awt.Color;
import java.awt.Font;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JPanel;

public class menu1 extends JFrame {

    JPanel panelColor = new JPanel();
    JPanel panelButton = new JPanel();

    JButton SButtont = new JButton("Strat");
    JButton AButtont = new JButton("About");
    JButton EButtont = new JButton("Exit");

    JLabel labelPm = new JLabel();

    public menu1(){
        setSize(1200, 800);
        setLocation(0,0);
        setDefaultCloseOperation(EXIT_ON_CLOSE);
        setLayout(null);
    
        //kinkong
        ImageIcon cartoonLIcon = new ImageIcon("Generated by Microsoft Copilot1.png");
        JLabel labelPm2_5 = new JLabel(cartoonLIcon);
        labelPm2_5.setSize(350, 400);
        labelPm2_5.setLocation(40, 300);

        //godzira
        ImageIcon cartoon = new ImageIcon("ดาวน์โหลด1.png");
        JLabel labeldino = new JLabel(cartoon);
        labeldino.setSize(350, 400);
        labeldino.setLocation(800, 340);

        //Background
        panelColor.setSize(1200, 800);
        panelColor.setLocation(0,0);
        panelColor.setBackground(new Color(170,170,170));

        //Button
        panelButton.setSize(700, 300);
        panelButton.setLocation(350, 350);
        panelButton.setLayout(null);
        panelButton.setBackground(new Color(170,170,170));

        setSButtont();
        setAButtont();
        setEButtont();
        setlabelPm();

        add(labelPm);
        add(labelPm2_5);
        add(labeldino);
        add(panelButton);
        add(panelColor);
    }

    public void setSButtont()
    {
        SButtont.setSize(350, 50);
        SButtont.setLocation(100, 50);
        SButtont.setFont(new Font("Arial", Font.BOLD,30));
        panelButton.add(SButtont);
    }

    void setAButtont()
    {
        AButtont.setSize(350, 50);
        AButtont.setLocation(100, 115);
        AButtont.setFont(new Font("Arial", Font.BOLD,30));
        panelButton.add(AButtont);
    }

    void setEButtont()
    {
        EButtont.setSize(350, 50);
        EButtont.setLocation(100, 180);
        EButtont.setFont(new Font("Arial", Font.BOLD,30));
        panelButton.add(EButtont);
    }

    void setlabelPm()
    {
        labelPm.setSize(1200, 300);
        labelPm.setLocation(470, 100);
        labelPm.setText("PM 2.5");
        labelPm.setFont(new Font("Arial",Font.BOLD,80));
    }
    
}
